[package]
name = "cryptobeca"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
sha3 = "0.10"
secp256k1 = "0.27.0"
rand = "0.8"
hex = "0.4"
dotenv = "0.15"